Complete TT9 with optional task
CheTigor/java-filmorate pull request #1
Opened 2023-05-11 15:30 UTC by CheTigor

2023-05-12 10:37 UTC, YazykovMikhail requested changes

2023-05-12 10:37 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                if (anotherFilm.equals(film)) {
неоднозначно, иметь одно опсиание и название и продолжительность, еще не значит являтся одним и тем же филтмом.
Этого условях жватит
 if (!films.containsKey(film.getId())) {
 и как раз в обраном случае стоит выбрасывать исклбчение что фильма с таким id не существуюет,

2023-05-12 10:37 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                if (anotherUser.equals(user)) {
думаю что стоит в equals проверять только login и email и name 
логин и email дллжны быть уникальны для пользователя.
А имя иногда используется для логина. 
А вот на дату рождения все равно.

2023-05-12 14:00 UTC, CheTigor commented
Я оставил в model только аннотацию @Data, так как теперь в controllers я сравниваю только по id, из-за этого, если id разный, то и объекты разные, не зависимо от их полей. Следовательно своя реализация equals больше не нужна.

2023-05-13 12:45 UTC, YazykovMikhail commented
Комментарии которые ты поправил, отмечай "решенными"

2023-05-13 12:48 UTC, YazykovMikhail approved these changes
Комментарии которые ты поправил, отмечай "решенными"

Так же ты не поправил логирвоание. Посмотри еще раз на мои комментарии по этому поводу и к следующей работе поправь

2023-05-13 12:48 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
Так же стоит обратить внимание на логирование.
Когда приходит запрос
и Когда уходит ответ.
Например
method() {
log.info("Reciered request PUT films, film: {}", film)
//тело метода
log.info("Reciered response film: {}", film)

}

2023-05-13 12:48 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Создание нового фильма");
просто логировать что было создание фтльма смысла нет, когда ты идешь смотреть на логи, значит у тебя что то сломалось и ты хочешь посмотреть что было в коде, а у тебя там "Создание нового фильма".
Пришел запрос такой то с такими то телом.
Ушел ответ такой то с таким то телом.

И если были между этим какие то бизнес операции (имя подставлялось в логин) тоже стоит залогитровать, что бы понимать что это произошло и какое значение получилось

2023-05-15 08:37 UTC, CheTigor commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                if (anotherFilm.equals(film)) {
Решено

2023-05-15 08:37 UTC, CheTigor commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                if (anotherUser.equals(user)) {
Решено

2023-05-15 08:37 UTC, CheTigor commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
Решено

2023-05-15 08:37 UTC, CheTigor commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Создание нового фильма");
Решено

2023-05-15 08:39 UTC, merged