feat: добавлена база данных на базе H2
CheTigor/java-filmorate pull request #4
Opened 2023-06-23 17:03 UTC by CheTigor

2023-06-24 19:02 UTC, YazykovMikhail reviewed
Откуда диаграмма взялась в мейне?)
В мейн ничего не должно попадать без ПР.
И так же изменения в README, они тоже уже в мастере
Это конечно не поправляй уже, на будущее имей ввиду

2023-06-24 19:32 UTC, YazykovMikhail requested changes
В целом не похо, молодец. БД не простая тема, но видно что норм понял, только возвращать фильмы стоит сразу со всеми полями. Как и любые другие обьеты с внешними ключами - это на будущее

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +ALTER TABLE "films_genre" ADD FOREIGN KEY ("film_id") REFERENCES "films"("id");
Добавляй ключи сразу при создании таблиц, где это возможно.
например ты создаешь первым User - потому что у него нет внешних ключи, а потом всех остальных с внешними ключами.

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "rating" (
назови лучше MPA, иначе не понятно какой имено это рейтинг

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +  "name" varchar
делай ограничения varchar(255)

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "friendship_status" (
Вообще этого в финальном задании нет. 
Это было промежуточное, посомтри, в финальном задании про статус ничего нет. 
Лучше пока убрать

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "film_likes" (
Можно делать вот так:

create table if not exists LIKES (
    user_id     int references USERS(user_id),
    film_id     int references FILMS(film_id ),

    PRIMARY KEY (user_id,film_id)
);
делать составной первичный ключи. 
потому что это значение будет уникальным, как вариант можешь попробовать. Но и так норм

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoImpl.java
> +    public User removeFriend(int id, int friendId) {
Для друзей сделай отдельное Dao

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    public Film addLike(int filmId, int userId) {
Для лайков сделай отдельное dao

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoImpl.java
> +        final User friend = getUserById(friendId);
Ты тут вызываешь только для прверки что он есть. 
Это дело сервиса, лучше это там делать.

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoImpl.java
> +        final User friend = getUserById(friendId);
Ты тут вызываешь только для прверки что он есть.
Это дело сервиса, лучше это там делать.

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        String sqlQuery = "select * from \"films\"";
Но у тея вернуться только поля которые находятся в таблице film, а остальные? 
Посмотри у тебя в моделт Film есть поля и из других таблиц

т.е вот так выглядит нарпимер этот запрос:

```
@Override
	public List<Film> getAll() {
		return jdbcTemplate.query("select * from FILMS f, MPA m where f.MPA_ID = m.MPA_ID", DbFilmStorage::makeFilm);
	}
	
```

Плюс ко всему в сервисе еще вот что:
```
@Override
	public List<Film> getAll() {
		final List<Film> films = super.getAll();
		genreStorage.load(films);
		return films;
	}
```
Т.е мы вызвваем еще репозиторий для жанров, что бф фильмы наполнить жанрами, ты спросишь почему мы в запросе не могли сразу смапить жанры? потому что там связь многие ко многим. И вернулось бы много одинаковых фильмов. 

Поэтому жанры мы должны отдельно добавлять в фльмы для возврата. 

или вот так:

```
@Override
	public void load(List<Film> films) {
		String inSql = String.join(",", Collections.nCopies(films.size(), "?"));
		final Map<Long, Film> filmById = films.stream().collect(Collectors.toMap(Film::getId, identity()));
		final String sqlQuery = "select * from GENRES g, FILM_GENRES fg where fg.GENRE_ID = g.GENRE_ID AND fg.FILM_ID in (" + inSql + ")";
		jdbcTemplate.query(sqlQuery, (rs) -> {
			final Film film = filmById.get(rs.getLong("FILM_ID"));
			film.addGenre(makeGenre(rs, 0));
		}, films.stream().map(StorageData::getId).toArray());
	}
```
	
Или получить все жанры и потом уже мапить на фильмы, но так не очень потому что таблица может быть очень большой, и не хватит памяти что бы получить все жанры и потом еще спамить на список фильмов.

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    public Film getFilmById(int id) {
Такая же логика будет и тут

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoImpl.java
> +    public User addFriend(int id, int friendId) {
если убрать статус, то будет все просто:

@Override
	public void addFriend(long userId, long friendId) {
		String sqlQuery = "merge into FRIENDS (USER_ID, FRIEND_ID) values (?, ?)";
		jdbcTemplate.update(sqlQuery, userId, friendId);
	}

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/GenreDaoImpl.java
> +    public Genre create(Genre genre) {
Жанры нельзя создать, они есть толко поумолчанию, создаются при старте приложения. 
Тут толкь методы get и getAll

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/RatingDaoImpl.java
> +    public Rating create(Rating rating) {
Mpa нельзя создать они создаются только пр истарте, тут только методы get и getAll

2023-06-24 19:32 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>      public User put(@Valid User user) {
@Valid лучше вынести в контроллер, нет смысла переходить в сервис если данные не валидны. 
Поправь везде

2023-06-24 19:42 UTC, CheTigor commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "friendship_status" (
В пункте "Добавление новой бизнес логики" есть вот такая фраза в подсказке - напоминалке:
"Не забудьте: у пользователей Filmorate должна быть возможность лайкать фильмы и добавлять друг друга в друзья с подтверждением дружбы."
Оставляем статусы?

2023-06-24 19:45 UTC, CheTigor commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoImpl.java
> +    public User removeFriend(int id, int friendId) {
Сделать отдельное Dao для методов связанных с друзьями и лайками? Просто модели Friend и LIke у меня нет, да и не нужны они. Я думал под каждую модель создаем DAO

2023-06-24 19:51 UTC, CheTigor commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        String sqlQuery = "select * from \"films\"";
В методе makeFilm я добавляю жанры и рейтинги, иначе бы не прошел проверку. Пойдет такая реализация, или реализовать ваш вариант?
Вот код метода:
private Film makeFilm(ResultSet rs) throws SQLException {
        int id = rs.getInt("id");
        String title = rs.getString("title");
        String description = rs.getString("description");
        LocalDate releaseDate = rs.getDate("release_date").toLocalDate();
        long duration = rs.getLong("duration");
        int rate = rs.getInt("rate");
        Rating rating = giveRating(rs.getInt("rating_id"));

        Film film = new Film(id, title, description, releaseDate, duration, rating);
        film.setRate(rate);

        SqlRowSet sql = jdbcTemplate.queryForRowSet(
                "select \"genre_id\" from \"films_genre\" where \"film_id\" = ?", id);
        while (sql.next()) {
            film.getGenres().add(giveGenre((sql.getInt("genre_id"))));
        }

        return film;
    }

2023-06-24 21:32 UTC, CheTigor commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS "friendship_status" (
Было принято решение оставить данную таблицу, так как в ТЗ необходимо подтверждать дружбу

2023-06-24 22:21 UTC, CheTigor commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoImpl.java
> +    public User removeFriend(int id, int friendId) {
Сделал отдельные Dao для методов: addLike, removeLike, addFriend, removeFriend

2023-06-24 22:30 UTC, CheTigor commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoImpl.java
> +    public User addFriend(int id, int friendId) {
Так как было принято решение оставить статус у дружбы, то тогда оставлю как есть, обсуждение закрою

2023-06-25 00:32 UTC, CheTigor commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        String sqlQuery = "select * from \"films\"";
В итоге сделал как вы показали, но плохо понимаю зачем разделять создания фильма в 2 класса... жанры в сервисе, остальное в filmDao, хотя оба метода находятся в filmDao

2023-06-25 20:24 UTC, merged